# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Hello, world!"
    echo "Node version: " `node --version`
    npm install sfdx-cli
    echo "Authenticating with Org"
    sfdx force:auth:jwt:grant --clientid 3MVG9LBJLApeX_PBOEVRs89aNZgKlbBizEoN4A4eUtu2zIMilxp4hK.wZXHcJtk7xoAppgvHQnQIEFzoZaHGa  --username michaelrelova@rockconnections.com.cx --jwtkeyfile certificates/server.key --setdefaultdevhubusername


  displayName: 'Install sfdx manually'
- task: sfpwowerscript-installsfdx-task@5
  displayName: Install SFDX
  inputs:
    isTelemetryEnabled: true
- task: sfpwowerscript-validatedxunlockedpackage-task@2
  displayName: Validates An Unlocked Package for Metadata Coverage
  inputs:
    package: 'force-di'
    isTelemetryEnabled: true

    
- task: sfpwowerscript-authenticateorg-task@7
  inputs:
    method: 'ServiceConnection'
    alias: 'HubOrg'
    isTelemetryEnabled: true

- task: sfpwowerscript-managescratchorg-task@5
  inputs:
    action: 'Create'
    config_file_path: 'config/project-scratch-def.json'
    alias: 'scratchorg'
    devhub_alias: 'HubOrg'
    maintainorg: 'delete'
    isTelemetryEnabled: true

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
